### ISSUE TITLE
reqeust: VueFireを用いたVue3 + Firebaseの開発

### ISSUE THREAD

**Issue by shinGangan** [shinGangan/comm_vue_nuxt#15]
### 概要

VueFireを用いたVue3 + Firebaseの開発

### 詳細

vue-router、Piniaの作者が作成しているライブラリに[VueFire](https://vuefire.vuejs.org/)というライブラリがある。
これはVue + Firebaseの開発を円滑に進めるものである。

ただ、本記事の入門記事はない(そもそも記事がない)。そこでどなたかに先駆者になってほしい。

### 備考欄

以下のような人が執筆してくれると嬉しいです。

- Vue2 / Vue3を業務で触っているがNuxt3は触ったことない人
- 2024年の目標がVue / Nuxt / フロント頑張ってみたいな人
- 先駆者になりたい人

**Comment by shinGangan** [comment]
### 運営コメント

執筆希望あれば @shinGangan をメンションしてください。アサインします。

**Comment by kspace-trk** [comment]
@shinGangan やります！(もう文章書いたのでいつでも出せます)

**Comment by shinGangan** [comment]
@kspace-trk 

ありがとうございます！執筆感謝します🙏

**Comment by shinGangan** [comment]
投稿タイミングは任意です。いつでも問題ございませんのでタイミングお任せいたしますー

**Comment by shinGangan** [comment]
#### Note: @shinGangan 

投稿確認後にイシューをクローズする

**Comment by kspace-trk** [comment]
@shinGangan 記事投稿しました！
https://zenn.dev/comm_vue_nuxt/articles/d17c38dfc3d54b

**Comment by shinGangan** [comment]
ありがとうございました！

closed #15
