### ISSUE TITLE
[追加希望]: kspace_trk

### ISSUE THREAD

**Issue by kspace-trk** [shinGangan/comm_vue_nuxt#18]
### Zenn User Name

kspace_trk

### X (formerly Twitter)

kspace_trk

### GitHub

kspace-trk

### 備考欄
https://github.com/shinGangan/comm_vue_nuxt/issues/15 の執筆をきっかけに参加したいです！ 🙆‍♂️

**Comment by shinGangan** [comment]
@kspace_trk

Publicationに招待しました。
Zenn登録済みメールアドレスに招待が来てるかと思いますので承認のほどお願い致します🙏

**Comment by kspace-trk** [comment]
@shinGangan 参加できました！ありがとうございます 🙆‍♂️

**Comment by shinGangan** [comment]
承認を確認したためイシューをクローズする
