### ISSUE TITLE
request: nuxt-vitestからnuxt/test-utilsへのマイグレーションしてみた

### ISSUE THREAD

**Issue by shinGangan** [shinGangan/comm_vue_nuxt#20]
### 概要

nuxt-vitestからnuxt/test-utilsへのマイグレーション

### 詳細

#19 の関連記事。本記事は **マイグレーション**にフォーカスを当てたものです。

#### Related

#19

**Comment by kspace-trk** [comment]
@shinGangan 書きたいです！

**Comment by shinGangan** [comment]
> @shinGangan 書きたいです！

@kspace-trk アサインdoneです 👍

**Comment by kspace-trk** [comment]
@shinGangan 書きました！！！！！！！
https://zenn.dev/comm_vue_nuxt/articles/1d35964c69ca1c

**Comment by shinGangan** [comment]
ありがとうございます🎉🎉

closed #20
