### ISSUE TITLE
[追加希望]: naonao70

### ISSUE THREAD

**Issue by NaokiHaba** [shinGangan/comm_vue_nuxt#24]
### Zenn User Name

naonao70

### X (formerly Twitter)

NaokiHaba

### GitHub

NaokiHaba

**Comment by shinGangan** [comment]
@NaokiHaba 

Publicationの招待を行いました！
登録メールに招待が来ていると思いますのでご確認のほどお願い致します 🙏

**Comment by NaokiHaba** [comment]
@shinGangan 
確認できましたmm

ご対応ありがとうございます！

**Comment by NaokiHaba** [comment]
Publication 参加できたので完了とする

**Comment by shinGangan** [comment]
@NaokiHaba 

執筆楽しみにしております！よろしくお願い致します〜🙏

**Comment by shinGangan** [comment]
> Publication 参加確認が取れたので完了とする

thx! 🙇
