### ISSUE TITLE
[追加希望]: petaxa

### ISSUE THREAD

**Issue by petaxa** [shinGangan/comm_vue_nuxt#32]
### Zenn User Name

petaxa

### X (formerly Twitter)

damenamepu

### GitHub

petaxa

### 備考欄

いちむらゆうまです。v-tokyoの感想レポ執筆予定です！

**Comment by shinGangan** [comment]
@petaxa 

ZennのPublicationへ招待しました！
登録されているメールアドレスに招待リンクが届いてると思いますので確認・承認のほどお願いいたします🙏

**Comment by shinGangan** [comment]
Publicationの承認を確認。
イシューをクローズします
