### ISSUE TITLE
write: `<NuxtRouteAnnouncer>`、`useRouteAnnouncer` の解説記事

### ISSUE THREAD

**Issue by yamanoku** [shinGangan/comm_vue_nuxt#38]
### 概要

`<NuxtRouteAnnouncer>`、`useRouteAnnouncer`がそれぞれどういうものなのか、実際の使い方についての解説記事を書く

### 詳細

[Nuxt3.12](https://nuxt.com/blog/v3-12)よりアクセシビリティ強化として[`<NuxtRouteAnnouncer>`](https://nuxt.com/docs/api/components/nuxt-route-announcer)、[`useRouteAnnouncer`](https://nuxt.com/docs/api/composables/use-route-announcer)がそれぞれ追加された。
`nuxt/a11y`の取り組みとして日本人向けの解説記事で内容を紹介したい。

### 備考欄

忘れるといかんので遅くとも今月中にはpublishしたい

**Comment by yamanoku** [comment]
useRouteAnnouncerがexportされてなかったためその修正を取り込んだ3.12.2のリリース待機中
https://github.com/nuxt/nuxt/pull/27531#issue-2346223771

**Comment by yamanoku** [comment]
月をまたいでしまいましたが公開しました 🙇🏼 
[SPA のアクセシビリティを強化する Nuxt の Route Announcer 機能](https://zenn.dev/comm_vue_nuxt/articles/feat-nuxt-route-announcer)

**Comment by shinGangan** [comment]
@yamanoku 

ありがとうございました！🙏
