### ISSUE TITLE
リクエスト: 初学者向けにコミュニティの一員として活動をするときに気をつけたいことをまとめる記事が欲しい

### ISSUE THREAD

**Issue by Ubugeeei** [shinGangan/comm_vue_nuxt#4]
リクエストテンプレできたらタイトルやフォーマットはテキトーに変更してください 🙏🏻 

キーワード
- 行動規範
- ファクトチェック
- 背景情報には気をつけること
- 攻撃されても攻撃しないこと
  - (反対意見は、いうべき.)

**Comment by shinGangan** [comment]
### 運営コメント

執筆希望あれば @shinGangan をメンションしてください。アサインします。

**Comment by Ubugeeei** [comment]
この記事で満たせていそうです。ありがとうございました。

[【初学者にこそ伝えたい】Vue.js コミュニティ入門](https://zenn.dev/comm_vue_nuxt/articles/vue-community)
