### ISSUE TITLE
[追加希望]: neletolus

### ISSUE THREAD

**Issue by neletolus** [shinGangan/comm_vue_nuxt#55]
### Zenn User Name

yohei_4

### X (formerly Twitter)

ra4n8ra6n

### GitHub

neletolus

**Comment by shinGangan** [comment]
@neletolus 

招待致しました！
Zenn登録のメールアドレスに承認メールが届いています。お手すきの際にご確認お願い致します。

**Comment by neletolus** [comment]
@shinGangan 
招待を受理いたしました！
ありがとうございます！
