### ISSUE TITLE
feat: cover画像 / アイコン画像がほしい

### ISSUE THREAD

**Issue by shinGangan** [shinGangan/comm_vue_nuxt#6]
## Context

cover画像、アイコン画像を設定したい。

**Comment by Ubugeeei** [comment]
情報が集まる、というキーワードに沿うて対象がいいな〜

人が集まるって意味で公園っぽいイメージにするとか、倉庫とか、ネットワークの中心とか

**Comment by shinGangan** [comment]
> 情報が集まる、というキーワードに沿う対象がいいな〜
> 
> 人が集まるって意味で公園っぽいイメージにするとか、倉庫とか、ネットワークの中心とか

イメージの認識合いますね。
私のイメージは芝生の公園 / 広場で人が集まっているイメージです

**Comment by Ubugeeei** [comment]
@shinGangan 

どうすか(トリミングして欲しいが)

![image](https://github.com/shinGangan/comm_vue_nuxt/assets/71201308/6acd683b-0e3e-4855-bf67-77f7606a650b)

**Comment by Ubugeeei** [comment]
人間が欲しいな

**Comment by Ubugeeei** [comment]
こんなものもできた

![image](https://github.com/shinGangan/comm_vue_nuxt/assets/71201308/ea351582-94f9-4cde-9198-955608465f55)

**Comment by shinGangan** [comment]
> こんなものもできた
> 
> ![image](https://private-user-images.githubusercontent.com/71201308/298955075-ea351582-94f9-4cde-9198-955608465f55.jpeg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDYwMjMyODQsIm5iZiI6MTcwNjAyMjk4NCwicGF0aCI6Ii83MTIwMTMwOC8yOTg5NTUwNzUtZWEzNTE1ODItOTRmOS00Y2RlLTkxOTgtOTU1NjA4NDY1ZjU1LmpwZWc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTIzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDEyM1QxNTE2MjRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02NmQ1YTYyZmYzMWNmODRlOWY2YWY0MTU0NDlkODAzMmY0ZWNiN2FiYTAzNGJlZDcxZDkxYzgzNjdmNDNhYmZjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.ujrIa3X01rZOJQPAJW2o4GXVEVRMKLX9OdFTQlQ9T3I)
> 
> ![image](https://private-user-images.githubusercontent.com/71201308/298955270-5aaeff0f-34db-4154-bcee-1ee7cdfbf6fc.jpeg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDYwMjMyODQsIm5iZiI6MTcwNjAyMjk4NCwicGF0aCI6Ii83MTIwMTMwOC8yOTg5NTUyNzAtNWFhZWZmMGYtMzRkYi00MTU0LWJjZWUtMWVlN2NkZmJmNmZjLmpwZWc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTIzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDEyM1QxNTE2MjRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00MzhhODc2ZDVkMThhODA1MjQyNjI0NGIwOGFmNDRkNzVlYzJlZTM3MTY5ZTUzOTFhMmUzOTcxODYxYjBlZjU1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.ULu_eq2kfC7rU_ULyiDG3Oj0AWqtKAL3m7AOwkEpxhA)

アイコンとしては上側が好きですね。
人がよりしっかりしているので、下画像はカバーに良さそう。

**Comment by Ubugeeei** [comment]
Hey, 兄さん、オーナーじゃないと設定できないっぽいので好きに設定して欲しいぜ

**Comment by shinGangan** [comment]
@Ubugeeei 

mission completed 🫡
カバーの方はちょっと引き気味にトリミングして置いてます(暫定的にはこれでもええかもです)

**Comment by Ubugeeei** [comment]
@shinGangan 

とっても良さそうです. ありがとうございました

**Comment by shinGangan** [comment]
他に追加対応ありそうですか？
なければ本イシューをクローズさせておきますー

**Comment by Ubugeeei** [comment]
一旦クローズでいいと思います！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！

**Comment by shinGangan** [comment]
closed.
