### ISSUE TITLE
write: UnoCSS について詳しく書く

### ISSUE THREAD

**Issue by kosuke222naito** [shinGangan/comm_vue_nuxt#62]
### 概要

UnoCSS の紹介記事の詳細編

### 詳細

#54 

詳細編を書こうとしたら紹介したいことが多すぎて、量が多くなってしまった。
そこで、

- 公式プリセット 
- 設定

の2つにわけることに。

公式プリセット: https://zenn.dev/comm_vue_nuxt/articles/what_is_unocss_official_presets
設定: https://zenn.dev/comm_vue_nuxt/articles/what_is_unocss_config

**Comment by kosuke222naito** [comment]
@shinGangan 

詳細編ですが、量が多すぎたので今度こそ分割しました🙇‍♂️

公式プリセット: https://zenn.dev/comm_vue_nuxt/articles/what_is_unocss_official_presets
設定: https://zenn.dev/comm_vue_nuxt/articles/what_is_unocss_config

公式 Playground を利用して実際に動かせるようなコードまで用意しましたが、誘導が下手な気がしています、、、
何かアドバイスあればいただきたいです。

お手すきの際に確認いただけるとありがたいです🙇‍♂️
よろしくお願いします！

**Comment by shinGangan** [comment]
@kosuke222naito 

今日、明日で確認してコメントします〜🙆

**Comment by kosuke222naito** [comment]
@shinGangan 

ほんとにありがとうございます！

>  私がレビュアーではなく読者だった場合「実際にUnoCSSを試すにはどのような環境構築をすればいいのだろう？」と感じます。例えば、Vite + Vue + UnoCSSの環境導入記事はどこかで執筆予定ですか？
それとも、特に執筆予定はないでしょうか。

今回は公式 Playground が提供されていることを推したい気持ちもあったり、横着したい気持ちもあって、、、
今後他のフレームワークとの比較を行う過程で必ず環境構築ははずなので、その際にまとめてみようかなと思っています！
issue 作成します、助言ありがとうございます🙇‍♂️

> 私が執筆者だった場合は型のimportは以下で記述するなと思います。
```ts
import type { Preset } from 'unocss';
// ...
```

ありがとうございます。
インライン type について理解が足りていませんでした。

https://zenn.dev/teppeis/articles/2023-04-typescript-5_0-verbatim-module-syntax
こちらの記事を読んで、GANGANさんの提案してくださった書き方の方がいい気がしているので修正します。
指摘ありがとうございます🙇‍♂️

**Comment by kosuke222naito** [comment]
> hトップの絵文字はchibivueインスパイアですかね？普段Zennで見かけないので華やかな印象を感じました

[Vue Begineers](https://zenn.dev/vue_beginners) さんの記事からパクらせていただきました笑
彼もきっと chibivue しているんでしょうね🤔

**Comment by shinGangan** [comment]
@kosuke222naito 

> 今後他のフレームワークとの比較を行う過程で必ず環境構築ははずなので、その際にまとめてみようかなと思っています！
issue 作成します、助言ありがとうございます🙇‍♂️

こちらについては執筆者が「読者に何を届けたい、何を目的として読んで欲しいか」という読み手視点がポイントになるので気にしすぎなくて良いかと思います🙆
本記事の場合 **公式 Playground が提供されていることを推したい気持ち** というのが(私は)伝わったので大丈夫かなと思いますー

> ありがとうございます。
インライン type について理解が足りていませんでした。

これは私が普段Nuxtを書いてるのもあっての指摘でした。そのためNITSで指摘しました。

**Comment by kosuke222naito** [comment]
@shinGangan 

指摘もらえるのは非常にありがたいので、なんでも嬉しいです
本当にいつもありがとうございます

もっかいチェックしてみて、今日の夜には #54 の方を公開しちゃいます！

**Comment by shinGangan** [comment]
@kosuke222naito 

LGTMです🎉

https://zenn.dev/comm_vue_nuxt/articles/what_is_unocss_official_presets

**Comment by shinGangan** [comment]
@kosuke222naito 

LGTMです🎉

https://zenn.dev/comm_vue_nuxt/articles/what_is_unocss_config

**Comment by shinGangan** [comment]
[確認] @kosuke222naito 

本イシューでレビューした記事は全て投稿済みですか？
もし投稿済みであればお手隙の際にイシューをクローズお願いします〜🙏

**Comment by kosuke222naito** [comment]
@shinGangan 

アッ
すみませんクローズ忘れてました

**Comment by shinGangan** [comment]
LGTMです🎉
