### ISSUE TITLE
[追加希望]: esttom

### ISSUE THREAD

**Issue by esttom** [shinGangan/comm_vue_nuxt#63]
### Zenn User Name

est

### GitHub

esttom

**Comment by shinGangan** [comment]
@esttom 

ZennのPublicationへ招待致しました！
Zenn登録のメールアドレスに招待リンクが届いてるかと思いますのでご確認お願い致します🙏

**Comment by esttom** [comment]
@shinGangan 

ありがとうございました。無事完了致しましたのでcloseさせていただきます。
