### ISSUE TITLE
[追加希望]: aoito

### ISSUE THREAD

**Issue by itoao** [shinGangan/comm_vue_nuxt#64]
### Zenn User Name

aoito

### GitHub

itoao

### 備考欄

自薦です。
ご確認のほどよろしくお願いいたします。

**Comment by Ubugeeei** [comment]
@itoao cc @shinGangan 

追加しました〜〜〜〜

**Comment by itoao** [comment]
@Ubugeeei cc: @shinGangan 
ありがとうございます！
招待確認できました✅

**Comment by shinGangan** [comment]
承認確認完了済みなので本イシューをクローズします
