### ISSUE TITLE
[追加希望]: yarai

### ISSUE THREAD

**Issue by mrs-y-arai** [shinGangan/comm_vue_nuxt#67]
### Zenn User Name

yarai

### X (formerly Twitter)

yuu_a_prog

### GitHub

mrs-y-arai

**Comment by shinGangan** [comment]
@mrs-y-arai 

ZennのPublicationに招待しました！
Zenn登録のメールアドレスに招待が届いていると思いますので後程ご確認よろしくお願い致します🙏

**Comment by mrs-y-arai** [comment]
@shinGangan 
参加しました！ありがとうございます。

**Comment by shinGangan** [comment]
追加を確認したので本イシューをクローズします
