### ISSUE TITLE
[追加希望]: hiro

### ISSUE THREAD

**Issue by hiroto0701** [shinGangan/comm_vue_nuxt#68]
### Zenn User Name

eneosgrandchild

### GitHub

hiroto0701

### 備考欄

宜しくお願いいたします🙇‍♂️

**Comment by shinGangan** [comment]
@hiroto0701 

ZennのPublicationに招待致しました。

Zenn登録のメールアドレスに招待が届いているかと思います。ご確認お願い致します！

**Comment by hiroto0701** [comment]
@shinGangan 

すみません確認遅くなりました！

承認ありがとうございます！
参加させていただきました。

早速で申し訳ないのですが、VueのSuspenseに関する記事を書きだめてて、レビューしていただきたいなと思っているのですがどのように進めたらよろしいでしょうか？

**Comment by shinGangan** [comment]
@hiroto0701 

レビューについては以下のフローで進めてもらえると助かります。

1. [Issues](https://github.com/shinGangan/comm_vue_nuxt/issues)で執筆希望イシューを起票する
    - **✍️ Want to write**という執筆希望用のテンプレートがあります。そちらを利用ください
2. イシュー起票後、コメント @shinGangan をメンションください。
    - 主に @shinGangan が把握するためです。3項時にまとめてもらっても大丈夫です。
3. 記事執筆後に記事のリンク(下書き)を添付し、合わせて @shinGangan のメンションをお願い致します。

**Comment by shinGangan** [comment]
### Note

Publicationへの追加確認済み。
上記QA解決後にイシューをクローズする

**Comment by hiroto0701** [comment]
@shinGangan 
記事執筆用のイシュー作成しました。

**Comment by shinGangan** [comment]
起票を確認したため本イシューをクローズ
