### ISSUE TITLE
Custom Elements × Vue について書いてほしい

### ISSUE THREAD

**Issue by ubugeeei** [shinGangan/comm_vue_nuxt#70]
### 概要

Custom Elements × Vue について書いてほしい

### 詳細

- そもそも Custom Elements とは
- Vue.js で Custom Elements を使う方法
- v3.5 で入った改善について

**Comment by yamanoku** [comment]
題材として興味ある（そこまで詳しい訳では無い）ので立候補します

**Comment by yamanoku** [comment]
@shinGangan @ubugeeei 
書き出してはいるのですがあまり話が広がらず悩んでおります…（[Vueの公式ドキュメント](https://ja.vuejs.org/guide/extras/web-components.html)の内容をなぞってるだけになりそう）

https://github.com/yamanoku/zenn-content/pull/32

ざっくりとで恐縮ですがこういう視点や話があったらいいかも、みたいなアドバイスいただきたいです 🙇🏼  🙇🏼  🙇🏼

**Comment by ubugeeei** [comment]
@yamanoku 

え、一通り読んでみましたが普通に良い感じだと思いました

そもそも ce 自体も、 Vue で ce を使うことも認知度がかなり低いと思うので、体系的にまとめられてるだけでかなり価値があると思いました

**Comment by ubugeeei** [comment]
そもそも今回は 3.5 で出た内容のまとめと、リキャップみたいなのがメインなはずなのでこういう感じで全然良くて、別の記事として具体的な活用例とかの説明があったりすると良いのかもしれない

**Comment by yamanoku** [comment]
@ubugeeei ありがとうございます！ 🙇🏼 
一人で書いててこれでいいのか自信なかったのですが、この方向性のまま書ききってみたいと思います 👍🏼

**Comment by yamanoku** [comment]
@shinGangan @ubugeeei 公開しましたー！
https://zenn.dev/comm_vue_nuxt/articles/improvements-to-custom-elements-in-vue3-5

**Comment by ubugeeei** [comment]
@yamanoku 

ありがとうございます！！！！！！！！！！！！！！！！！！！！！
