### ISSUE TITLE
write: Vue 3.5: パフォーマンスと開発体験を革新する包括的アップデート

### ISSUE THREAD

**Issue by NaokiHaba** [shinGangan/comm_vue_nuxt#74]
### 概要

Vue 3.5: パフォーマンスと開発体験を革新する包括的アップデート

### 詳細

正式リリースされた Vue 3.5に関する日本の記事が少ない。

今回は多くの新機能が追加されたのでより多くの人に新機能や改善点を伝えたい

**Comment by NaokiHaba** [comment]
@shinGangan 
下書きを共有させていただきます🙇
お手隙にご確認の程よろしくお願いいたします
https://zenn.dev/comm_vue_nuxt/articles/8b8b959f416166

**Comment by shinGangan** [comment]
@NaokiHaba 

明日確認しますね～！🙆‍♀️

**Comment by shinGangan** [comment]
@NaokiHaba 

遅れてすみません！
レビューコメントを下記に記載しました！お手隙の際に確認お願い致します🙏


> [!NOTE]
> Qから始まるやつは疑問です。不要だったらスルーしてください。
>
> Sから始まるやつは提案です。採用については一任です。
>
> prefix無しのものはレビュー指摘です

#### 2. SSRの改善

- Lazy Hydrationは解説だけで1本書けるくらいの量があると認識しています。そのため、現説明のみで理解できる人はかなりVueに精通している人の気がします。こちらは補足の記事への動線を追加したり、アコーディオンで解説を挟む方が良いと思います。
(前提読者として他言語ユーザーやVue自体に詳しくない(業務では使っているけど精通しているわけでない)を切る前提であれば不要な指摘です。パスしてください)

#### 4. その他の機能追加

- S. 完全な新規追加と既存APIの更新が混ざっているように感じました。「機能追加」という文脈においては間違っていませんが、新規/更新を分けた方が読み手ライクならと感じました。こちらいかがでしょうか、ご見解をお聞きしてみたいです！

#### Deferred Teleport

- S. Teleportそのものを知っているユーザーがどのくらいいるのか分かりません(そもそも知らない恐れすらある)。そのため、Teleportの公式ドキュメントへのリンクを掲載するのはいかがでしょうか。

#### 5. Reactivity System の改善

- Q. もし私が読み手だった場合「その他って最後に来るケースが多いけど途中にあるんだ」と思います。こちらは何か意図があってこの順番なのですか？

**Comment by NaokiHaba** [comment]
@shinGangan 
レビューありがとうございます！！

**Comment by NaokiHaba** [comment]
@shinGangan 

> @NaokiHaba
> 
> 遅れてすみません！ レビューコメントを下記に記載しました！お手隙の際に確認お願い致します🙏
> 
> Note
> 
> Qから始まるやつは疑問です。不要だったらスルーしてください。
> 
> Sから始まるやつは提案です。採用については一任です。
> 
> prefix無しのものはレビュー指摘です
> 
> #### 2. SSRの改善
> * Lazy Hydrationは解説だけで1本書けるくらいの量があると認識しています。そのため、現説明のみで理解できる人はかなりVueに精通している人の気がします。こちらは補足の記事への動線を追加したり、アコーディオンで解説を挟む方が良いと思います。
>   (前提読者として他言語ユーザーやVue自体に詳しくない(業務では使っているけど精通しているわけでない)を切る前提であれば不要な指摘です。パスしてください)
> 
> #### 4. その他の機能追加
> * S. 完全な新規追加と既存APIの更新が混ざっているように感じました。「機能追加」という文脈においては間違っていませんが、新規/更新を分けた方が読み手ライクならと感じました。こちらいかがでしょうか、ご見解をお聞きしてみたいです！
> 
> #### Deferred Teleport
> * S. Teleportそのものを知っているユーザーがどのくらいいるのか分かりません(そもそも知らない恐れすらある)。そのため、Teleportの公式ドキュメントへのリンクを掲載するのはいかがでしょうか。
> 
> #### 5. Reactivity System の改善
> * Q. もし私が読み手だった場合「その他って最後に来るケースが多いけど途中にあるんだ」と思います。こちらは何か意図があってこの順番なのですか？

---

修正が遅くなり申し訳ありません。

レビューいただいた内容を踏まえて、全体的により読み手に優しい内容に修正しました🙇

> #### 2. SSRの改善
> * Lazy Hydrationは解説だけで1本書けるくらいの量があると認識しています。そのため、現説明のみで理解できる人はかなりVueに精通している人の気がします。こちらは補足の記事への動線を追加したり、アコーディオンで解説を挟む方が良いと思います。
>   (前提読者として他言語ユーザーやVue自体に詳しくない(業務では使っているけど精通しているわけでない)を切る前提であれば不要な指摘です。パスしてください)

ご指摘のとおり、この記事を読んで欲しい読者層は、Vue を使い始めたばかりの初学者や、業務で使っているが Vue にあまり精通していない中級者です。

そのため、そもそもの `Lazy Hydration` とは何かを説明する必要があると感じましたので、Lazy Hydration の説明を追加しました🙇


> #### 4. その他の機能追加
> * S. 完全な新規追加と既存APIの更新が混ざっているように感じました。「機能追加」という文脈においては間違っていませんが、新規/更新を分けた方が読み手ライクならと感じました。こちらいかがでしょうか、ご見解をお聞きしてみたいです！
> 
> #### 5. Reactivity System の改善
> * Q. もし私が読み手だった場合「その他って最後に来るケースが多いけど途中にあるんだ」と思います。こちらは何か意図があってこの順番なのですか？

おっしゃる通りです。

新規/更新を分けた方が、「新規機能の話と改善の話がごっちゃになり、どっちが新規でどっちが改善なのかわかりにくい」ということがなくなると思います。

そのため、新規/更新をより読み手に優しい順番にしました。

> #### Deferred Teleport
> * S. Teleportそのものを知っているユーザーがどのくらいいるのか分かりません(そもそも知らない恐れすらある)。そのため、Teleportの公式ドキュメントへのリンクを掲載するのはいかがでしょうか。

ご指摘のとおりです。

`Teleport` を利用した方が、そもそも想定読者にあてはまる人が少ないため、Teleport の公式ドキュメントへのリンクを追加しました🙇

**Comment by NaokiHaba** [comment]
@shinGangan 
レビューありがとうございました🙏
投稿準備して投稿完了次第連携させていただきます

**Comment by shinGangan** [comment]
@NaokiHaba 

LGTMです〜！
もし投稿前に再度レビュー必要であればお気軽にメンションくださいませ。

**Comment by NaokiHaba** [comment]
@shinGangan 
投稿完了しました🚀
https://zenn.dev/comm_vue_nuxt/articles/8b8b959f416166

**Comment by shinGangan** [comment]
@NaokiHaba 

LGTMです🎉

**Comment by shinGangan** [comment]
投稿を確認したのでイシューをクローズする。
