### ISSUE TITLE
[追加希望]: jiyuujin

### ISSUE THREAD

**Issue by jiyuujin** [shinGangan/comm_vue_nuxt#75]
### Zenn User Name

jiyuujin

### GitHub

jiyuujin

### 備考欄

Best regards, I have applied to create my account mm

**Comment by shinGangan** [comment]
@jiyuujin 

Publicationにアカウントを追加しました！
Zenn登録アドレスに招待メールが届いてると思いますのでお手隙の際にご確認お願い致します🙏

**Comment by jiyuujin** [comment]
@shinGangan ありがとうございます、確認できました mm

**Comment by shinGangan** [comment]
メンバー追加を確認したため本イシューをクローズする
