### ISSUE TITLE
[追加希望]: takumaru

### ISSUE THREAD

**Issue by takuma-ru** [shinGangan/comm_vue_nuxt#76]
### Zenn User Name

takumaru

### X (formerly Twitter)

takumaru_2222

### GitHub

takuma-ru

**Comment by shinGangan** [comment]
@takuma-ru 

Zenn Publicationへ招待しました。
Zenn登録のメールアドレスに招待リンクが届いておりますのでご確認お願い致します！

**Comment by takuma-ru** [comment]
@shinGangan 
招待いただきありがとうございます！
Publicationへの参加完了いたしました。

**Comment by shinGangan** [comment]
Zennへの追加を確認したのでクローズします。
