### ISSUE TITLE
[追加希望]: tokuda109

### ISSUE THREAD

**Issue by tokuda109** [shinGangan/comm_vue_nuxt#8]
### Zenn User Name

tokuda109

### X (formerly Twitter)

tokuda109

### GitHub

tokuda109

**Comment by shinGangan** [comment]
@tokuda109 

メンバーに追加致しました。お手隙の際にご確認お願い致します🙏

**Comment by tokuda109** [comment]
@shinGangan 

![Screenshot 2024-01-17 at 13 29 33](https://github.com/shinGangan/comm_vue_nuxt/assets/108762/2914a301-fe93-4348-9512-6b614ed75eaf)

紐づけに失敗してしまいました

> Publicationには未所属のPublicationを指定することはできません

こちらがコミットになります: https://github.com/tokuda109/zenn.dev/commit/53ad5ec96485de662709efd04b780bfdd22140e5

**Comment by shinGangan** [comment]
@tokuda109 

メンバーへの招待メールが届いてませんでしょうか。
おそらく招待メールより承認 -> Publicationへの紐付けの順で行えば大丈夫かと思います。

こちらサイドで確認したところ「承認待ち」のステータスとなっておりました！

**Comment by tokuda109** [comment]
@shinGangan 
確認ありがとうございます!
招待メールが届いていました、無事紐づけできました!!

**Comment by shinGangan** [comment]
確認済み。チケットをクローズ
