### ISSUE TITLE
[追加希望]: hashiba

### ISSUE THREAD

**Issue by hashibadaiki** [shinGangan/comm_vue_nuxt#88]
### Zenn User Name

baan

### X (formerly Twitter)

baan_nasebanaru

### GitHub

hashibadaiki

### 備考欄

Vueの発展に少しでも寄与できれば!と思いますmm
ご対応よろしくお願いします。

**Comment by shinGangan** [comment]
@hashibadaiki 

Zenn Publicationへ招待しました！
Zenn登録アドレスに招待リンクが届いていますのでお手隙の際にご確認お願いいたします🙏

**Comment by shinGangan** [comment]
#### 運営コメント

承認を確認したためイシューをクローズする。

**Comment by hashibadaiki** [comment]
@shinGangan 
確認できました！ご対応ありがとうございました！
