### ISSUE TITLE
[追加希望]: ryoAccount

### ISSUE THREAD

**Issue by ryoAccount** [shinGangan/comm_vue_nuxt#89]
### Zenn User Name

ryocv

### X (formerly Twitter)

RYO_nami

### GitHub

ryoAccount

### 備考欄

会社でもZenn記事書かないといけなくて、すぐには動き出せないのですが、年内目標で何か書く気はあります。
私も微力ながら何かしら参加させていただければと思います。

**Comment by shinGangan** [comment]
@ryoAccount 

Zenn Publicationへ招待しました！
Zenn登録のメールアドレスに招待リンクが届いていますのでお手隙の際にご確認お願い致します🙏

**Comment by ryoAccount** [comment]
@shinGangan 
ありがとうございます!!
参加できました✨

**Comment by shinGangan** [comment]
#### 運営コメント

追加を確認したので本イシューをクローズします
