### ISSUE TITLE
[追加希望]: asip2k25

### ISSUE THREAD

**Issue by asip** [shinGangan/comm_vue_nuxt#9]
### Zenn User Name

asip2k25

### X (formerly Twitter)

asip2k25

### GitHub

asip

### 備考欄

asip2k25 or asip (こと Ashida)と申します。

https://qiita.com/asip2k25
https://zenn.dev/asip2k25

にて、Vue.js/Nuxt3まわり を含め、
いくつか記事を書いています。

Vue.js / Nuxt3 まわりを盛り上げて
いきたいと思っていますので、
よろしければPublicationのメンバーに
追加ください。

とりあえず、過去記事(現状に合わせ、
修正済みですor修正します)を追加する
予定です。

よろしくお願いします。

**Comment by shinGangan** [comment]
@asip 

メンバー追加しました。お手隙の際にご確認お願い致します🙏

**Comment by shinGangan** [comment]
追加を確認したためクローズする

**Comment by asip** [comment]
@shinGangan

メンバーへの追加、ありがとうございます。よろしくお願いします。
