### ISSUE TITLE
[追加希望]: kon_karin

### ISSUE THREAD

**Issue by konkarin** [shinGangan/comm_vue_nuxt#90]
### Zenn User Name

kon_karin

### X (formerly Twitter)

k0n_karin

### GitHub

konkarin

**Comment by ubugeeei** [comment]
@konkarin cc @shinGangan 

招待しました〜〜〜 (ご確認ください)

**Comment by konkarin** [comment]
@shinGangan ありがとうございます🥳

**Comment by konkarin** [comment]
よく見たら対応してくれたの @ubugeeei さんだった😇😇😇(ありがとうございます
