### ISSUE TITLE
[追加希望]: Gaakuu

### ISSUE THREAD

**Issue by Gaakuu** [shinGangan/comm_vue_nuxt#91]
### Zenn User Name

gaakuu

### X (formerly Twitter)

gaakuu__

### GitHub

Gaakuu

### 備考欄

よろしくお願いします！

**Comment by shinGangan** [comment]
@Gaakuu 

Publicationに招待しました！Zenn登録アドレスに招待メールが来ているのでご確認お願いします〜🙏

**Comment by Gaakuu** [comment]
@shinGangan 
ありがとうございます！招待メールからパブリケーションに参加いたしました！

**Comment by shinGangan** [comment]
#### 運営コメント

承認を確認したのでイシューをクローズします。
