### ISSUE TITLE
write: Nuxtはどうやってfile-based routingを実現しているか

### ISSUE THREAD

**Issue by konkarin** [shinGangan/comm_vue_nuxt#93]
### 概要

Nuxtはどうやってfile-based routingを実現しているか

### 備考欄

空いてたので https://qiita.com/advent-calendar/2024/nuxt-and-unjs の13日の枠として公開しようと思います！

### レビューの必要性

@shinGangan 初Publication投稿なのでレビューお願いしたいです！ぜんぜん急ぎじゃないのでお時間あるときにお願いします🫡
https://zenn.dev/comm_vue_nuxt/articles/62b8dea3a018f9

**Comment by konkarin** [comment]
@shinGangan 
アドカレ終わる25日までにはレビューお願いしたいです！🙏
急ぎじゃないと言いつつ急かしてすみません！😭

**Comment by shinGangan** [comment]
@konkarin 

対応漏れてました！本当に申し訳ないです🙏
明日時間取れそうなので明日中にレビューします！

**Comment by shinGangan** [comment]
@konkarin 

遅れて申し訳ありません。以下レビューコメントです！
(以下は確認系が主ですので返答優先度は下げてもらって大丈夫です。気にせず公開してください)

### nits

Storybookの方もNuxt Tailiwindと表記を合わせて **Nuxt Storybook** の方が良いと思います。

> tailwindcssやstorybookを使っている方は [Nuxt Tailwind](https://tailwindcss.nuxtjs.org/)や[@nuxtjs/storybook](https://storybook.nuxtjs.org/)で馴染みがあるかもしれません。

### 念の為の確認

本記事は「devモード時のfile based routingの挙動を追った記事」という認識ですが、こちら認識齟齬ありますでしょうか。
build時の挙動、SSR/SSG/SPAなどの挙動差は今回は深く追っていない認識です。

**Comment by konkarin** [comment]
@shinGangan 
ありがとうございます！確認して1点目は直しました👍

2点目はそのとおりです！特に断りはないですが、文脈で伝わりそうなのと、レンダリングモードによって差分も無いと思う（多分）ので、一旦は記載せずに公開しようと思います。
気になってきたので、このあと調べてみます🫡

**Comment by shinGangan** [comment]
@konkarin 

ご回答ありがとうございます！認識齟齬がなくてよかったです🙏
はい、こちら記載なしで良いと思います。

> 2点目はそのとおりです！特に断りはないですが、文脈で伝わりそうなのと、レンダリングモードによって差分も無いと思う（多分）ので、一旦は記載せずに公開しようと思います。
