### ISSUE TITLE
Nuxt のドキュメンタリーを見て日本語で記事を書いてほしい

### ISSUE THREAD

**Issue by ubugeeei** [shinGangan/comm_vue_nuxt#94]
### 概要

Nuxt のドキュメンタリーを見て日本語で記事を書いてほしい

### 詳細

https://x.com/supabase/status/1869427407003812135

**Comment by ubugeeei** [comment]
@kosuke222naito

お願いします！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！

**Comment by naitokosuke** [comment]
@ubugeeei 
はい！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！

**Comment by naitokosuke** [comment]
https://zenn.dev/kosuke_naito/articles/nuxt_mini_documentary_supabase

書きました！

**Comment by ubugeeei** [comment]
天才すぎ
